#!/usr/bin/env bash
set -euo pipefail

REQ_FILE="${1:-requirements.txt}"
WHEEL_DIR="artifacts/wheels/linux"
MODEL_DIR="artifacts/models"
MANIFEST_DIR="artifacts/manifests"
MANIFEST_PATH="${MANIFEST_DIR}/sha256sums.txt"

mkdir -p "${WHEEL_DIR}" "${MODEL_DIR}" "${MANIFEST_DIR}"

python -m pip download \
  --only-binary=:all: \
  --dest "${WHEEL_DIR}" \
  -r "${REQ_FILE}"

if [[ -n "${PA_MODEL_SOURCE_DIR:-}" ]]; then
  cp -a "${PA_MODEL_SOURCE_DIR}/." "${MODEL_DIR}/"
else
  echo "PA_MODEL_SOURCE_DIR not set; skipping model staging."
fi

{
  echo "# sha256 manifest for artifacts (generated by build scripts)"
  find artifacts/wheels artifacts/models -type f ! -name ".gitkeep" -print0 \
    | sort -z \
    | xargs -0 sha256sum
} > "${MANIFEST_PATH}"

echo "Artifacts ready:"
echo "  Wheels:   ${WHEEL_DIR}"
echo "  Models:   ${MODEL_DIR}"
echo "  Manifest: ${MANIFEST_PATH}"
