param(
    [string]$RequirementsFile = "requirements.txt"
)

$WheelDir = "artifacts\wheels\windows"
$ModelDir = "artifacts\models"
$ManifestDir = "artifacts\manifests"
$ManifestPath = Join-Path $ManifestDir "sha256sums.txt"

New-Item -ItemType Directory -Force -Path $WheelDir, $ModelDir, $ManifestDir | Out-Null

python -m pip download --only-binary=:all: --dest $WheelDir -r $RequirementsFile

if ($env:PA_MODEL_SOURCE_DIR) {
    Copy-Item -Recurse -Force -Path (Join-Path $env:PA_MODEL_SOURCE_DIR "*") -Destination $ModelDir
} else {
    Write-Host "PA_MODEL_SOURCE_DIR not set; skipping model staging."
}

$files = Get-ChildItem -Path "artifacts\wheels","artifacts\models" -Recurse -File | Where-Object { $_.Name -ne ".gitkeep" }
$hashLines = @("# sha256 manifest for artifacts (generated by build scripts)")
foreach ($f in $files) {
    $hash = (Get-FileHash -Algorithm SHA256 -Path $f.FullName).Hash
    $hashLines += "$hash  $($f.FullName)"
}

Set-Content -Path $ManifestPath -Value $hashLines -Encoding ASCII

Write-Host "Artifacts ready:"
Write-Host "  Wheels:   $WheelDir"
Write-Host "  Models:   $ModelDir"
Write-Host "  Manifest: $ManifestPath"
